### ISSUE TITLE
Cant connect to PPC Smart Meter Gateway

### ISSUE THREAD

**Issue by rk-h** [dadley/node-red-contrib-smgw#1]
Hi. I have the same SMG. But from different energy supplier. So maybe login name or password are following other rules. I can login With TRuDI but I can't find something like the 'HAN-Profile field'. The TRuDI login creds are not working. Do you have any ideas or hints? The information that you must connect to http://192.168.1.200/cgi-bin/hanservice.cgi - is it publicly available?

**Comment by duswie** [comment]
Unfortunately, I cannot help with other energy suppliers. `https://192.168.1.200/cgi-bin/hanservice.cgi` is the default setting from the manufacturer's [documentation](https://www.ppc-ag.de/wp-content/uploads/2022/01/Handbuch-fuer-Verbraucher.pdf). If you find out anything, please share it here.
